server:
  port: 9988

spring:
  application:
    name: admin-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  management.U';/.,UUendpoints.web.exposure.include=*
  management.endpoint.health.show-details=always