max:
  value: Ahmed Ali Ibrahim
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/installment_upgrade?serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
