spring:
  datasource:
    url: jdbc:mysql://localhost:3307/supplier_upgrade?serverTimezone=UTC
    username: root
    password: my-secret-pw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
