server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/common-config
  profiles:
    active: native
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
