server:
  port: 8888

spring:
  application:
  name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/common-config
  config:
    activate:
      on-profile:


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
